### ISSUE TITLE
Module not signed

### ISSUE THREAD

**Issue by johnsmunoz** [POSSA/freepbx-Call-Statistics#17]
FreePBX keeps telling me that this module is not signed.  This is the link with the instructions on how to get your module signed by FreePBX
http://wiki.freepbx.org/pages/viewpage.action?pageId=29753662

**Comment by lgaetz** [comment]
We are aware of the situation and there are no immediate plans to address this. If you want to use the module you will have to ignore the signature warning(s).

**Comment by opoplawski** [comment]
Would be nice to have this addressed.
