### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by MShoaib67** [POSSA/freepbx-Call-Statistics#19]
Hi,
After Uploading when try to enable the module it gives error. Please see the attached image.

![image](https://cloud.githubusercontent.com/assets/10461055/14139004/d6b286ce-f689-11e5-9144-090f89a95d2a.png)

**Comment by lgaetz** [comment]
Looks like you have to download it again, use the upload module button in Module Admin. Note that this module has not been touched in years and you may have issues using with FreePBX 13.
